import { User, Plan, Sponsor } from "./types";

const rawMockUsers: any[] = [
  {
    id: "user-1",
    name: "Sofía Ruiz",
    age: 28,
    profession: "Diseñadora Gráfica",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
    bio: "Me acabo de mudar a Málaga desde Galicia. No conozco a mucha gente aquí y me encantaría hacer un grupo de amigos para salir a caminar, tomar café y charlar sobre arte y diseño.",
    interests: ["Senderismo", "Café", "Diseño", "Fotografía", "Picnics"]
  },
  {
    id: "user-2",
    name: "Alejandro Gómez",
    age: 29,
    profession: "Desarrollador de Software",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
    bio: "Apasionado de los juegos de mesa modernos (Catan, Carcassonne, Dixit). Busco gente con buena onda para organizar tardes divertidas de juegos y risas en Málaga, sin ninguna otra pretensión que pasar un buen rato.",
    interests: ["Juegos de Mesa", "Cine", "Cerveza Artesana", "Tecnología"]
  },
  {
    id: "user-3",
    name: "Carmen Torres",
    age: 26,
    profession: "Estudiante de Doctorado en Historia",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150",
    bio: "Me encanta el senderismo cultural, los clubs de lectura y las tertulias interesantes. Busco conocer gente apasionada por la cultura para aprender de otros y forjar nuevas amistades genuinas.",
    interests: ["Lectura", "Historia", "Senderismo", "Museos", "Charlas"]
  },
  {
    id: "user-4",
    name: "Mateo Silva",
    age: 22,
    profession: "Estudiante de Bellas Artes",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
    bio: "Me gusta pintar al aire libre (plein air) y explorar la hermosa luz de Málaga. Busco un grupo de gente joven interesada en pintar, dibujar en libretas (urban sketching) o simplemente visitar galerías juntos.",
    interests: ["Dibujo", "Arte", "Museos", "Cafeterías", "Música"]
  },
  {
    id: "user-5",
    name: "Elena Marín",
    age: 27,
    profession: "Psicóloga Infantil",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150",
    bio: "Tengo un perro mestizo super amigable llamado 'Chispa'. Me encanta la naturaleza, la meditación y el yoga. Busco compañeras y compañeros para paseos perrunos, yoga en la playa o charlas conscientes en la naturaleza.",
    interests: ["Perros", "Yoga", "Naturaleza", "Meditación", "Senderismo"]
  },
  {
    id: "user-6",
    name: "Lucas Herrero",
    age: 30,
    profession: "Cocinero",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150",
    bio: "Trabajo en el Soho. En mi tiempo libre me encanta probar nuevos sabores, ir de tapas tradicionales y cocinar para otros. Busco gente que ame la gastronomía para hacer rutas de tapeo o probar brunchs relajados de fin de semana.",
    interests: ["Gastronomía", "Cocina", "Brunch", "Tapas", "Música en Vivo"]
  },
  {
    id: "user-7",
    name: "Martina Ortiz",
    age: 29,
    profession: "Traductora de Idiomas",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
    bio: "Hablo inglés, francés y un poco de italiano. Practico yoga y me encantan los picnics en la playa al atardecer. Busco conocer gente de diversos orígenes para hacer intercambios de idiomas y planes relajados al aire libre.",
    interests: ["Idiomas", "Yoga", "Picnics", "Playa", "Viajes"]
  },
  {
    id: "user-8",
    name: "Hugo Pineda",
    age: 28,
    profession: "Guía de Turismo Activo",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150",
    bio: "Me conozco los mejores senderos de la provincia (Sierra de las Nieves, Mijas, Axarquía). Busco organizar grupos pequeños para hacer rutas los fines de semana, disfrutar de la fauna local y luego comernos un buen arroz campero.",
    interests: ["Senderismo", "Montaña", "Fotografía", "Naturaleza", "Comida"]
  },
  {
    id: "user-9",
    name: "Valeria Castillo",
    age: 24,
    profession: "Florista",
    avatar: "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=150",
    bio: "Amante de las plantas, las manualidades y la cerámica de autor. Me gustaría conectar con gente inquieta para ir a talleres, hacer rutas botánicas o simplemente reunirnos a tejer o moldear arcilla con un café de especialidad.",
    interests: ["Cerámica", "Plantas", "Talleres", "Café", "Manualidades"]
  },
  {
    id: "user-10",
    name: "Daniel Santos",
    age: 25,
    profession: "Fotógrafo de Bodas",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150",
    bio: "Después de estar todo el día detrás de la cámara con el trabajo, me apetece hacer fotografía artística y salidas nocturnas para capturar la Vía Láctea. Me encantaría compartir esta afición con otros aficionados, sin importar el nivel.",
    interests: ["Fotografía", "Astronomía", "Noche", "Senderismo", "Cine"]
  },
  {
    id: "user-11",
    name: "Lucía Vargas",
    age: 25,
    profession: "Arquitecta de Interiores",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=150",
    bio: "Me apasiona la arquitectura tradicional andaluza, los museos y el urbanismo. Me gustaría crear un grupo para hacer visitas culturales de fin de semana, explorar monumentos y debatir sobre arte y diseño.",
    interests: ["Arquitectura", "Arte", "Museos", "Fotografía", "Diseño"]
  },
  {
    id: "user-12",
    name: "Adrián Benítez",
    age: 27,
    profession: "Fisioterapeuta",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150",
    bio: "Juego al pádel de forma amateur y me encanta el vóley playa en la Malagueta. Busco gente dinámica que quiera organizar partidillos de pádel o pachangas de vóley de forma regular, ideal para divertirse y hacer ejercicio relajado.",
    interests: ["Pádel", "Vóley", "Deporte", "Playa", "Charlas"]
  },
  {
    id: "user-13",
    name: "Sara Peña",
    age: 23,
    profession: "Bióloga Marina",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=150",
    bio: "Me apasiona el mar, el buceo y la astronomía. Organizo a menudo quedadas nocturnas para observar estrellas y lluvias de meteoros desde calas tranquilas. Me encantaría compartir este espacio con personas curiosas.",
    interests: ["Astronomía", "Buceo", "Playa", "Naturaleza", "Ciencia"]
  },
  {
    id: "user-14",
    name: "Pablo Ortega",
    age: 30,
    profession: "Librero y Editor",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150",
    bio: "Propietario de una pequeña librería con encanto. Me fascinan el cine clásico, la literatura y el buen té. Busco crear tertulias literarias periódicas o grupos para ir a ver cine de autor y debatir amistosamente después.",
    interests: ["Lectura", "Cine", "Té", "Debates", "Historia"]
  },
  {
    id: "user-15",
    name: "Clara Méndez",
    age: 26,
    profession: "Veterinaria",
    avatar: "https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?auto=format&fit=crop&q=80&w=150",
    bio: "Me encantan todos los animales y el paddle surf. Suelo ir al Pedregalejo a remar bien temprano cuando el mar parece un espejo. Busco compañeros/as para hacer paddle surf matutino y desayunar luego unos espetos o pitufos.",
    interests: ["Paddle Surf", "Animales", "Playa", "Desayuno", "Deporte"]
  },
  {
    id: "user-16",
    name: "Jorge Navarro",
    age: 22,
    profession: "Graduado en Ingeniería Industrial",
    avatar: "https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&q=80&w=150",
    bio: "Aficionado a la bicicleta de carretera, la historia de la provincia de Málaga y el ajedrez. Busco personas interesadas en hacer rutas tranquilas de ciclismo de un par de horas o jugar unas partidas de ajedrez en un parque o café.",
    interests: ["Ajedrez", "Ciclismo", "Historia", "Naturaleza", "Café"]
  },
  {
    id: "user-17",
    name: "Noa Ferrer",
    age: 30,
    profession: "Diseñadora de Moda",
    avatar: "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=150",
    bio: "Me apasiona la moda vintage, la música alternativa y los mercadillos de segunda mano. Busco gente con quien recorrer el rastro del fin de semana, visitar tiendas retro y compartir cafés charlando sobre cultura urbana.",
    interests: ["Mercadillos", "Moda Retro", "Conciertos", "Café", "Diseño"]
  },
  {
    id: "user-18",
    name: "Manuel Jurado",
    age: 21,
    profession: "Estudiante de Náutica",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=150",
    bio: "Estudio náutica y me apasiona el mar. Me encanta pasear por el Muelle Uno, jugar al ajedrez al aire libre y hablar de barcos. Busco amigos para echar unas partidas y dar paseos tranquilos.",
    interests: ["Ajedrez", "Navegación", "Paseos", "Muelle Uno", "Charlas"]
  },
  {
    id: "user-19",
    name: "Irene Soler",
    age: 24,
    profession: "Periodista Cultural",
    avatar: "https://images.unsplash.com/photo-1520341280432-4749d4d7bcf9?auto=format&fit=crop&q=80&w=150",
    bio: "Amante de la dramaturgia, los conciertos acústicos y la poesía. Me gusta descubrir el talento local en locales alternativos de Málaga. Busco grupo para ir al teatro, conciertos íntimos y debatir sobre la escena cultural.",
    interests: ["Teatro", "Música Acústica", "Poesía", "Cine", "Charlas"]
  },
  {
    id: "user-20",
    name: "David Morales",
    age: 29,
    profession: "Entrenador de Calistenia",
    avatar: "https://images.unsplash.com/photo-1542327897-d73f4005b533?auto=format&fit=crop&q=80&w=150",
    bio: "Entreno al aire libre y promuevo un estilo de vida activo y saludable. Busco organizar entrenamientos grupales divertidos en las barras de la playa y terminar con un picnic saludable compartiendo batidos y buen rollo.",
    interests: ["Calistenia", "Picnics", "Deporte", "Playa", "Nutrición"]
  }
];

export const mockUsers: User[] = rawMockUsers.map((user, idx) => ({
  ...user,
  kronos: [120, 85, 150, 45, 95, 110, 60, 130, 30, 75, 140, 50, 115, 90, 125, 40, 85, 70, 105, 100][idx % 20]
}));

export const mockPlans: Plan[] = [

  {
    id: "plan-verify-demo",
    creatorId: "user-1",
    title: "Torneo de Vóley Playa",
    description: "Un torneo amistoso en la playa de la Malagueta. ¡Tenemos que repartir los kronos a los que vinieron!",
    categoria: "Deportes",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Ayer",
    ubicacion: "Playa de la Malagueta",
    asistentesConfirmados: ["user-1", "user-2", "user-3", "user-4", "user-5", "user-6"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [
      {
        id: "m-vd-1",
        role: "system",
        senderName: "Sistema",
        text: "¡El evento ha finalizado! Por favor, verifica la asistencia para entregar los Kronos.",
        timestamp: "Ayer, 20:00"
      },
      {
        id: "m-vd-2",
        role: "user",
        senderName: "Carlos Gómez",
        text: "¡Estuvo genial el torneo!",
        timestamp: "Ayer, 20:30"
      }
    ],
    isPast: true,
    attendanceVerified: false
  },

  {
    id: "plan-past-auto-1",
    creatorId: "user-1",
    title: "Cena en pizzería - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Gastronomía",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 7 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-1","user-5","user-11","user-15","user-16","user-3"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-1","user-5","user-11","user-15","user-16","user-3"]
  },
  {
    id: "plan-past-auto-2",
    creatorId: "user-2",
    title: "Ruta de senderismo - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 8 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-2","user-8","user-19","user-18","user-9"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-2","user-8","user-19","user-18","user-9"]
  },
  {
    id: "plan-past-auto-3",
    creatorId: "user-3",
    title: "Visita a museo - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Cultura",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 1 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-3","user-11","user-13"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-3","user-11","user-13"]
  },
  {
    id: "plan-past-auto-4",
    creatorId: "user-4",
    title: "Tarde de juegos de mesa - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Ocio",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 6 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-4","user-9","user-16","user-20"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-4","user-9","user-16","user-20"]
  },
  {
    id: "plan-past-auto-5",
    creatorId: "user-5",
    title: "Clase de yoga - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Bienestar",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 9 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-5","user-17","user-15","user-16","user-1"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-5","user-17","user-15","user-16","user-1"]
  },
  {
    id: "plan-past-auto-6",
    creatorId: "user-6",
    title: "Taller de fotografía - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Arte",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 4 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-6","user-4","user-3"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-6","user-4","user-3"]
  },
  {
    id: "plan-past-auto-7",
    creatorId: "user-7",
    title: "Cata de cervezas - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Gastronomía",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 4 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-7","user-1","user-9","user-15","user-20","user-6","user-17"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-7","user-1","user-9","user-15","user-20","user-6","user-17"]
  },
  {
    id: "plan-past-auto-8",
    creatorId: "user-8",
    title: "Partido de fútbol - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 6 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-8","user-4","user-9","user-7","user-1","user-6","user-20"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-8","user-4","user-9","user-7","user-1","user-6","user-20"]
  },
  {
    id: "plan-past-auto-9",
    creatorId: "user-9",
    title: "Paseo en bicicleta - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 8 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-9","user-8","user-14"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-9","user-8","user-14"]
  },
  {
    id: "plan-past-auto-10",
    creatorId: "user-10",
    title: "Concierto local - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Música",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 1 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-10","user-17","user-1","user-12","user-19","user-13","user-14"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-10","user-17","user-1","user-12","user-19","user-13","user-14"]
  },
  {
    id: "plan-past-auto-11",
    creatorId: "user-11",
    title: "Tarde de cine - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Cultura",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 10 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-11","user-8","user-6","user-12","user-4","user-17","user-1"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-11","user-8","user-6","user-12","user-4","user-17","user-1"]
  },
  {
    id: "plan-past-auto-12",
    creatorId: "user-12",
    title: "Taller de cocina - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Gastronomía",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 2 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-12","user-1","user-20","user-19","user-2","user-3","user-4"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-12","user-1","user-20","user-19","user-2","user-3","user-4"]
  },
  {
    id: "plan-past-auto-13",
    creatorId: "user-13",
    title: "Picnic en el parque - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Ocio",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 8 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-13","user-6","user-9","user-7"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-13","user-6","user-9","user-7"]
  },
  {
    id: "plan-past-auto-14",
    creatorId: "user-14",
    title: "Día de playa - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Naturaleza",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 8 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-14","user-6","user-9"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-14","user-6","user-9"]
  },
  {
    id: "plan-past-auto-15",
    creatorId: "user-15",
    title: "Visita al jardín botánico - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Naturaleza",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 8 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-15","user-14","user-1","user-7","user-6","user-19","user-13"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-15","user-14","user-1","user-7","user-6","user-19","user-13"]
  },
  {
    id: "plan-past-auto-16",
    creatorId: "user-16",
    title: "Club de lectura - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Cultura",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 6 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-16","user-7","user-13","user-8"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-16","user-7","user-13","user-8"]
  },
  {
    id: "plan-past-auto-17",
    creatorId: "user-17",
    title: "Clase de baile - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Deporte",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 10 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-17","user-11","user-16"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-17","user-11","user-16"]
  },
  {
    id: "plan-past-auto-18",
    creatorId: "user-18",
    title: "Tarde de bolos - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Ocio",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 1 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-18","user-17","user-4","user-9","user-6"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-18","user-17","user-4","user-9","user-6"]
  },
  {
    id: "plan-past-auto-19",
    creatorId: "user-19",
    title: "Excursión a la montaña - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 8 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-19","user-15","user-4"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-19","user-15","user-4"]
  },
  {
    id: "plan-past-auto-20",
    creatorId: "user-20",
    title: "Paseo por el puerto - Histórico",
    description: "Un evento increíble que ya ha ocurrido. Generado automáticamente.",
    categoria: "Ocio",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 9 meses",
    ubicacion: "Málaga",
    asistentesConfirmados: ["user-20","user-8","user-2","user-19","user-1"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-20","user-8","user-2","user-19","user-1"]
  },

  {
    id: "plan-past-3",
    creatorId: "user-2",
    title: "Torneo de Pádel",
    description: "Torneo amistoso en las pistas de Inacua.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 3 semanas",
    ubicacion: "Inacua Málaga",
    asistentesConfirmados: ["user-2", "user-3", "user-4", "user-5"],
    maxAsistentes: 4,
    bannerUrl: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-2", "user-3", "user-4", "user-5"]
  },
  {
    id: "plan-past-4",
    creatorId: "user-3",
    title: "Visita al Alcazaba",
    description: "Recorrido histórico por la Alcazaba y Gibralfaro.",
    categoria: "Cultura",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Hace 1 mes",
    ubicacion: "Entrada Alcazaba",
    asistentesConfirmados: ["user-3", "user-1", "user-6", "user-7", "user-8"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1549491689-d102e3b3337a?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-3", "user-1", "user-6", "user-8"]
  },
  {
    id: "plan-past-5",
    creatorId: "user-4",
    title: "Taller de Cocina Andaluza",
    description: "Aprendiendo a hacer el gazpacho perfecto y otros platos.",
    categoria: "Gastronomía",
    duracion: "2.5 horas",
    kronoValor: 25,
    fecha: "Hace 2 meses",
    ubicacion: "Mercado de Huelin",
    asistentesConfirmados: ["user-4", "user-1", "user-2", "user-9"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1556910103-1c02745a8720?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: false
  },
  {
    id: "plan-past-6",
    creatorId: "user-5",
    title: "Cine de Verano",
    description: "Proyección al aire libre en la playa de la Malagueta.",
    categoria: "Cultura",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 2 semanas",
    ubicacion: "Playa de la Malagueta",
    asistentesConfirmados: ["user-5", "user-10", "user-11", "user-12", "user-13", "user-14"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-5", "user-10", "user-11", "user-12", "user-13", "user-14"]
  },
  {
    id: "plan-past-7",
    creatorId: "user-6",
    title: "Intercambio de Idiomas",
    description: "Tarde de inglés y español tomando algo en el centro.",
    categoria: "Educación",
    duracion: "1.5 horas",
    kronoValor: 15,
    fecha: "Hace 5 días",
    ubicacion: "Morrissey's Irish Pub",
    asistentesConfirmados: ["user-6", "user-1", "user-2", "user-15", "user-16"],
    maxAsistentes: 12,
    bannerUrl: "https://images.unsplash.com/photo-1577563908411-50cb989766a3?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-6", "user-1", "user-15", "user-16"]
  },
  {
    id: "plan-past-8",
    creatorId: "user-7",
    title: "Ruta de la Tapa",
    description: "Probando las mejores tapas de Teatinos.",
    categoria: "Gastronomía",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Hace 10 días",
    ubicacion: "Teatinos",
    asistentesConfirmados: ["user-7", "user-8", "user-9", "user-10"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1525169994326-8c4391e92d24?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-7", "user-8", "user-9", "user-10"]
  },
  {
    id: "plan-past-9",
    creatorId: "user-8",
    title: "Yoga al amanecer",
    description: "Sesión de yoga para empezar el día con energía.",
    categoria: "Bienestar",
    duracion: "1 hora",
    kronoValor: 10,
    fecha: "Hace 4 días",
    ubicacion: "Parque del Oeste",
    asistentesConfirmados: ["user-8", "user-1", "user-17", "user-18"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: false
  },
  {
    id: "plan-past-10",
    creatorId: "user-1",
    title: "Limpieza de Playa",
    description: "Acción voluntaria para limpiar la playa de Sacaba.",
    categoria: "Voluntariado",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Hace 1 mes",
    ubicacion: "Playa de Sacaba",
    asistentesConfirmados: ["user-1", "user-11", "user-12", "user-19", "user-20"],
    maxAsistentes: 15,
    bannerUrl: "https://images.unsplash.com/photo-1618477461853-cf6ed80fbea5?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-1", "user-11", "user-12", "user-19", "user-20"]
  },

  {
    id: "plan-past-1",
    creatorId: "user-1",
    title: "Cata de Vinos en el Soho",
    description: "Una tarde increíble probando vinos locales.",
    categoria: "Gastronomía",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Hace 1 semana",
    ubicacion: "La Deriva, Soho",
    asistentesConfirmados: ["user-1", "user-2", "user-3", "user-4"],
    maxAsistentes: 5,
    bannerUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: false,
  },
  {
    id: "plan-past-2",
    creatorId: "user-1",
    title: "Ruta en Bici por la Costa",
    description: "Recorrimos la costa hasta el Rincón de la Victoria.",
    categoria: "Deportes",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Hace 2 semanas",
    ubicacion: "Muelle Uno",
    asistentesConfirmados: ["user-1", "user-5"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1471506480208-91b3a4cc78be?auto=format&fit=crop&q=80&w=800",
    chatHistory: [],
    isPast: true,
    attendanceVerified: true,
    asistentesValidados: ["user-1", "user-5"]
  },
  {
    id: "plan-0",
    creatorId: "user-4",
    title: "Hackathon de Espetup",
    description: "Buscamos a 4 personas más para formar un equipo de 5 en el hackathon de Espetup. Vamos a programar, idear y crear proyectos geniales. ¡Anímate y únete a nosotros!",
    categoria: "Cultura",
    duracion: "12 horas",
    kronoValor: 120,
    fecha: "Hoy",
    ubicacion: "El Rayo Verde - Avda. Louis Pasteur, 47, Campus de Teatinos, Málaga.",
    asistentesConfirmados: ["user-4"],
    maxAsistentes: 5,
    bannerUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800",
    chatHistory: [
      {
        id: "m-0-1",
        role: "system",
        senderName: "Sistema",
        text: "Chat del grupo para el Hackathon de Espetup.",
        timestamp: "Hace 1 hora"
      }
    ]
  },
  {
    id: "plan-1",
    creatorId: "user-1",
    title: "Paseo por el Paseo Marítimo y Helado",
    description: "Una tarde tranquila para conocernos dando un paseo por el Paseo Marítimo de la Malagueta. Caminaremos un par de kilómetros charlando de todo un poco y luego nos tomaremos un helado de los de toda la vida mientras vemos el atardecer. ¡Trae buen humor y calzado cómodo!",
    categoria: "Deportes",
    duracion: "1.5 horas",
    kronoValor: 15,
    fecha: "Este Sábado a las 18:30",
    ubicacion: "Entrada del Centro Pompidou (El Cubo de colores)",
    asistentesConfirmados: ["user-1", "user-6", "user-7", "user-15"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    chatHistory: [
      {
        id: "m-1",
        role: "system",
        senderName: "Sistema",
        text: "¡Bienvenido al canal del plan! Coordinemos la quedada aquí.",
        timestamp: "Ayer"
      },
      {
        id: "m-2",
        role: "user",
        senderId: "user-1",
        senderName: "Sofía Ruiz",
        senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
        text: "¡Hola a todos! Qué alegría ver que os habéis apuntado. Quedamos en las puertas del Pompidou, ¿os viene bien la hora?",
        timestamp: "10:30"
      },
      {
        id: "m-3",
        role: "user",
        senderId: "user-6",
        senderName: "Lucas Herrero",
        senderAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150",
        text: "¡Buenas! Sí, a mí me parece una hora perfecta. Así evitamos las horas de más calor.",
        timestamp: "10:45"
      },
      {
        id: "m-4",
        role: "assistant",
        senderName: "Gravita AI",
        text: "¡Hola Sofía, Lucas y equipo! ☀️ Qué plan tan fantástico para disfrutar del clima malagueño. Recordad que si queréis una merienda deliciosa antes del paseo, la mítica pastelería **Casa Kiki** tiene sucursal en Málaga con palmeras gigantes perfectas para compartir. ¿A qué heladería tenéis pensado ir al final?",
        timestamp: "10:46"
      }
    ]
  },
  {
    id: "plan-2",
    creatorId: "user-2",
    title: "Tarde de Juegos de Mesa Modernos",
    description: "Tarde de juegos de mesa en formato cooperativo y competitivo ligero (Dixit, Catan, Carcassonne, Código Secreto). No hace falta saber jugar, explicamos las reglas en 5 minutos con mucha paciencia. El plan es charlar, reírse y picar algo mientras echamos unas partidas.",
    categoria: "Gastronomía",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Este Domingo a las 17:00",
    ubicacion: "Comic Stores de Calle Trinidad Grund (Soho)",
    asistentesConfirmados: ["user-2", "user-4", "user-16"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&q=80&w=800",
    chatHistory: [
      {
        id: "m-1",
        role: "system",
        senderName: "Sistema",
        text: "Chat del grupo de Juegos de Mesa.",
        timestamp: "Hace 2 días"
      },
      {
        id: "m-2",
        role: "user",
        senderId: "user-2",
        senderName: "Alejandro Gómez",
        senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
        text: "Traeré el Dixit y el Carcassonne. ¿Alguien quiere proponer algún juego especial?",
        timestamp: "Ayer"
      },
      {
        id: "m-3",
        role: "user",
        senderId: "user-4",
        senderName: "Mateo Silva",
        senderAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
        text: "¡Yo me apunto con el Dixit! Nunca he jugado al Carcassonne pero me encantaría aprender.",
        timestamp: "12:15"
      },
      {
        id: "m-4",
        role: "assistant",
        senderName: "Gravita AI",
        text: "¡Qué gran selección de juegos! 🎲 El Dixit es excelente para romper el hielo de forma creativa. Si necesitáis un extra de energía, podéis pasaros por **Waw Cafe** para pillar unos cafés de especialidad o cookies increíbles para llevar. ¡A divertirse mucho!",
        timestamp: "12:16"
      }
    ]
  },
  {
    id: "plan-3",
    creatorId: "user-3",
    title: "Paseo Cultural por el Málaga Musulmana",
    description: "Un recorrido cultural a pie por los exteriores de la Alcazaba, el Teatro Romano y el casco histórico, comentando datos históricos y leyendas fascinantes de nuestra ciudad. Terminaremos charlando y tomando un té verde en una tetería acogedora. Apto para todas las edades.",
    categoria: "Cultura",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Próximo Martes a las 11:00",
    ubicacion: "Junto a la Pirámide de Cristal en Calle Alcazabilla",
    asistentesConfirmados: ["user-3", "user-11", "user-14", "user-18"],
    maxAsistentes: 12,
    bannerUrl: "https://images.unsplash.com/photo-1568849676085-51415703900f?auto=format&fit=crop&q=80&w=800",
    chatHistory: [
      {
        id: "m-1",
        role: "system",
        senderName: "Sistema",
        text: "Bienvenidos al recorrido cultural de la Málaga Musulmana.",
        timestamp: "Ayer"
      }
    ]
  },
  {
    id: "plan-4",
    creatorId: "user-4",
    title: "Urban Sketching: Dibujar el Soho",
    description: "Una quedada tranquila para dibujar las esquinas, grafitis y fachadas del Soho malagueño. No importa el nivel, cada uno dibuja a su ritmo en su libreta con rotuladores, acuarelas o lápiz. El propósito es compartir el proceso creativo, dar consejos sencillos de dibujo y charlar relajadamente.",
    categoria: "Naturaleza",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Jueves a las 17:30",
    ubicacion: "Plaza de la Marina (Junto a la Oficina de Turismo)",
    asistentesConfirmados: ["user-4", "user-1", "user-11", "user-17"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-5",
    creatorId: "user-5",
    title: "Senderismo Suave por los Montes de Málaga",
    description: "Una caminata de unos 6 km con desnivel mínimo por el sendero de El Torrijos. Disfrutaremos del aire libre entre pinos, el olor de la sierra y la compañía. Trae bocadillo o fruta para hacer un pícnic a mitad del recorrido. Aceptamos perros amigables de compañía.",
    categoria: "Juegos",
    duracion: "4 horas",
    kronoValor: 40,
    fecha: "Este Sábado a las 09:30",
    ubicacion: "Aparcamiento del Ecomuseo Lagar de Torrijos",
    asistentesConfirmados: ["user-5", "user-8", "user-13"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-6",
    creatorId: "user-6",
    title: "Ruta de Brunch de Especialidad en Waw Cafe",
    description: "Vamos a probar el increíble brunch de Waw Cafe: tostadas de masa madre, huevos benedict, tartas caseras y un café de especialidad preparado con mucho mimo. Un plan excelente para los amantes del café y las buenas mañanas de fin de semana, conversando de forma pausada y acogedora.",
    categoria: "Bienestar",
    duracion: "1.5 horas",
    kronoValor: 15,
    fecha: "Este Sábado a las 10:30",
    ubicacion: "Puerta de Waw Cafe (Málaga Centro)",
    asistentesConfirmados: ["user-6", "user-1", "user-9", "user-17"],
    maxAsistentes: 6,
    bannerUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcDfU6p5d3TxPgaCDAnb3jpjBUXQWD6OsSdAR4gtR6gA&s=10",
    chatHistory: [
      {
        id: "m-1",
        role: "user",
        senderId: "user-6",
        senderName: "Lucas Herrero",
        senderAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150",
        text: "Hola! He reservado mesa para 6 en Waw Cafe para que no nos quedemos fuera. Tienen opciones veganas y sin gluten riquísimas.",
        timestamp: "Hace 2 horas"
      },
      {
        id: "m-2",
        role: "user",
        senderId: "user-9",
        senderName: "Valeria Castillo",
        senderAvatar: "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=150",
        text: "¡Ay, perfecto Lucas! Su café de especialidad es de lo mejor de la ciudad. ¡Qué ganas!",
        timestamp: "Hace 1 hora"
      }
    ]
  },
  {
    id: "plan-7",
    creatorId: "user-7",
    title: "Yoga y Estiramientos al Atardecer",
    description: "Sesión grupal de yoga suave y estiramientos conscientes sobre la arena de la playa de Pedregalejo. No necesitas experiencia, solo una esterilla o toalla grande de playa. Terminaremos la sesión contemplando las luces del atardecer en silencio y compartiendo una charla de té reconfortante.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Miércoles a las 20:00",
    ubicacion: "Frente al Balneario de Pedregalejo (en la arena)",
    asistentesConfirmados: ["user-7", "user-5", "user-13"],
    maxAsistentes: 12,
    bannerUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-8",
    creatorId: "user-8",
    title: "Senderismo por la Sierra de Mijas",
    description: "Caminata de nivel medio por los senderos de la sierra, disfrutando de unas vistas de infarto a toda la costa del Sol. Ideal para desconectar del asfalto urbano, respirar el olor a pino y romero, y conocer gente aventurera en un clima relajado de compañerismo.",
    categoria: "Gastronomía",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Este Domingo a las 08:30",
    ubicacion: "Aparcamiento de la Cantera de los Arenales",
    asistentesConfirmados: ["user-8", "user-5", "user-10"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-9",
    creatorId: "user-9",
    title: "Taller Informal de Arcilla y Cerámica",
    description: "Quedada en un taller para moldear tazas o macetas con arcilla secado al aire. Traeremos arcilla básica y algunas herramientas simples para compartir. Lo importante no es crear una obra de museo, sino la textura, el proceso manual relajante y las risas compartidas entre amigos.",
    categoria: "Cultura",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Sábado de la próxima semana a las 17:00",
    ubicacion: "Parque de Huelin (Mesas de picnic de madera)",
    asistentesConfirmados: ["user-9", "user-1", "user-4", "user-11"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1565192647048-f997ded87958?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-10",
    creatorId: "user-10",
    title: "Fotografía Nocturna por el Centro Histórico",
    description: "Salida para capturar el alma nocturna de Málaga con nuestras cámaras o teléfonos móviles. Jugaremos con las luces de Calle Larios, las sombras de la Catedral y el misticismo del Teatro Romano iluminado. Compartiremos trucos de exposición y composición sobre la marcha.",
    categoria: "Naturaleza",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Próximo Viernes a las 21:30",
    ubicacion: "Bajo la Estatua del Marqués de Larios",
    asistentesConfirmados: ["user-10", "user-1", "user-4"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-11",
    creatorId: "user-11",
    title: "Visita al Museo Picasso y Café",
    description: "Vamos a visitar la exposición permanente de Picasso en su ciudad natal. Disfrutaremos del palacio renacentista de Buenavista y de sus increíbles obras. Al salir, iremos a tomar un té o café para intercambiar impresiones de forma amigable y sincera sobre las piezas.",
    categoria: "Juegos",
    duracion: "1.5 horas",
    kronoValor: 15,
    fecha: "Próximo Domingo a las 11:30",
    ubicacion: "Entrada del Museo Picasso (Calle San Agustín)",
    asistentesConfirmados: ["user-11", "user-4", "user-3", "user-14"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1580136579312-94651dfd596d?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-12",
    creatorId: "user-12",
    title: "Partidillo de Pádel de Nivel Principiante",
    description: "Buscamos dos jugadores/as de nivel iniciación o principiante bajo para completar una pista de pádel doble de 1h y media. Nada de competitividad excesiva ni frustraciones, el objetivo es sudar un poco, divertirnos, aprender y tomar algo fresco después de jugar.",
    categoria: "Bienestar",
    duracion: "2.5 horas",
    kronoValor: 25,
    fecha: "Próximo Lunes a las 19:30",
    ubicacion: "Club de Pádel El Candado (Málaga Este)",
    asistentesConfirmados: ["user-12", "user-20"],
    maxAsistentes: 4,
    bannerUrl: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-13",
    creatorId: "user-13",
    title: "Atardecer Astronómico y Picnic en la Playa",
    description: "Quedada en el Peñón del Cuervo para hacer un picnic al atardecer. Traeré un telescopio pequeño portátil para observar los primeros planetas de la noche y algunas constelaciones si el cielo acompaña. Trae tu toalla de playa, bocadillo y mucha curiosidad estelar.",
    categoria: "Deportes",
    duracion: "2.5 horas",
    kronoValor: 25,
    fecha: "Próximo Sábado a las 20:30",
    ubicacion: "Playa del Peñón del Cuervo (Junto al peñón gigante)",
    asistentesConfirmados: ["user-13", "user-10", "user-15", "user-18"],
    maxAsistentes: 12,
    bannerUrl: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-14",
    creatorId: "user-14",
    title: "Tertulia Literaria y Té en Calma",
    description: "Tertulia relajada sobre literatura andaluza y universal en un rincón con encanto. No hay que leerse ningún libro obligatorio; cada asistente comparte su libro preferido de los últimos meses, lee su fragmento favorito en voz alta y comentamos las ideas entre tazas de té templado.",
    categoria: "Gastronomía",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Jueves a las 18:00",
    ubicacion: "Mesas del Parque de Málaga (Cerca de la fuente de Génova)",
    asistentesConfirmados: ["user-14", "user-3", "user-19"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-15",
    creatorId: "user-15",
    title: "Paddle Surf y Desayuno en Pedregalejo",
    description: "Saldremos con las tablas a dar un paseo por el mar de 8:30 a 9:30, aprovechando el mar plato de la mañana. Después nos sentaremos en el paseo marítimo a tomarnos un buen desayuno de pitufos con tomate y café. Posibilidad de alquilar tabla en las escuelas de la zona.",
    categoria: "Cultura",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Este Sábado a las 08:30",
    ubicacion: "La playa frente al balneario de Pedregalejo",
    asistentesConfirmados: ["user-15", "user-7", "user-12"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1517022812141-23620dba5c23?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-16",
    creatorId: "user-16",
    title: "Ciclismo Relajado de Carretera",
    description: "Una ruta ciclista suave de ida y vuelta de unos 30 km hasta el Rincón de la Victoria, rodando siempre pegados al mar por el paseo habilitado y carriles adecuados. Iremos a un ritmo relajado que permita mantener conversación y pararemos a tomar una tarta en el camino.",
    categoria: "Naturaleza",
    duracion: "2.5 horas",
    kronoValor: 25,
    fecha: "Este Domingo a las 09:00",
    ubicacion: "Frente a la Antigua Estación de Ferrocarriles de Málaga",
    asistentesConfirmados: ["user-16", "user-18"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-17",
    creatorId: "user-17",
    title: "Ruta de Rastro Vintage y Antigüedades",
    description: "Paseo dominguero recorriendo los puestos de antigüedades, libros antiguos, vinilos de música retro y curiosidades del rastro de Málaga. Un plan divertido para curiosear objetos singulares del pasado y terminar charlando sentados en una soleada terraza del muelle.",
    categoria: "Juegos",
    duracion: "1.5 horas",
    kronoValor: 15,
    fecha: "Este Domingo a las 11:00",
    ubicacion: "Puerta principal del Palacio de Deportes J. M. Martín Carpena",
    asistentesConfirmados: ["user-17", "user-1", "user-19"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1488459711626-d6df2296a22d?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-18",
    creatorId: "user-18",
    title: "Partidas de Ajedrez al Aire Libre",
    description: "Una tarde de ajedrez bajo las pérgolas del Palmeral de las Sorpresas. Traeré un par de tableros de ajedrez reglamentarios. Partidas rápidas y amistosas para todas las edades y niveles. Ideal para agilizar la mente, aprender nuevas jugadas y charlar relajados rodeados de barcos.",
    categoria: "Bienestar",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Martes a las 17:30",
    ubicacion: "Palmeral de las Sorpresas (Muelle Dos, bancos del centro)",
    asistentesConfirmados: ["user-18", "user-3", "user-16"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-19",
    creatorId: "user-19",
    title: "Tarde de Teatro Micro y Cañas Sin",
    description: "Vamos a ver un par de obras cortas (microteatro) de autores locales en el centro de Málaga. Son formatos rápidos, intensos y muy divertidos de 15 minutos de duración. Al terminar, buscaremos una terraza cercana para charlar y comentar las puestas en escena.",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Sábado a las 19:30",
    ubicacion: "Plaza de la Merced (Junto a la estatua de Picasso sentado)",
    asistentesConfirmados: ["user-19", "user-1", "user-4", "user-17"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-20",
    creatorId: "user-20",
    title: "Calistenia en Grupo y Picnic de Batidos",
    description: "Entrenamiento colectivo adaptado a cualquier condición física en las barras de ejercicio de la playa de Huelin. Haremos ejercicios de fuerza corporal, estiramientos divertidos y luego compartiremos batidos, zumos de frutas naturales y un picnic saludable sentados en el césped.",
    categoria: "Gastronomía",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Este Sábado a las 11:00",
    ubicacion: "Zona de Calistenia del Paseo Marítimo de Huelin",
    asistentesConfirmados: ["user-20", "user-12", "user-15"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-21",
    creatorId: "user-1",
    title: "Merienda de Palmeras Gigantes en Casa Kiki",
    description: "¡No puedes decir que vives en Málaga si no has compartido una palmera gigante de Casa Kiki! Quedamos para merendar una de sus famosas palmeras de hojaldre con chocolate y yema, ideal para trocear en grupo y devorar mientras nos reímos y compartimos anécdotas en la tarde.",
    categoria: "Cultura",
    duracion: "1.5 horas",
    kronoValor: 15,
    fecha: "Próximo Miércoles a las 17:30",
    ubicacion: "Establecimiento de Casa Kiki (Málaga Este)",
    asistentesConfirmados: ["user-1", "user-2", "user-6", "user-9"],
    maxAsistentes: 6,
    bannerUrl: "https://casakiki.com/wp-content/uploads/2026/03/casa-kiki-palmeras-rellenas-gigantes.jpg",
    chatHistory: [
      {
        id: "m-1",
        role: "user",
        senderId: "user-1",
        senderName: "Sofía Ruiz",
        senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
        text: "¡Qué ganas de palmera de yema tostada! ¿Quién más se apunta?",
        timestamp: "Hace 1 día"
      }
    ]
  },
  {
    id: "plan-22",
    creatorId: "user-5",
    title: "Tarde de Meditación de Plenitud",
    description: "Sesión grupal para conectar con la calma interna en el Parque del Morlaco. Haremos una respiración guiada, un escaneo corporal tumbados sobre el césped y luego una caminata silenciosa entre árboles. Perfecto para rebajar el ritmo mental y conectar desde el silencio pacífico.",
    categoria: "Naturaleza",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Sábado a las 18:00",
    ubicacion: "Entrada del Parque Forestal El Morlaco",
    asistentesConfirmados: ["user-5", "user-7", "user-13"],
    maxAsistentes: 10,
    bannerUrl: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-23",
    creatorId: "user-6",
    title: "Visita Gastronómica al Mercado de Atarazanas",
    description: "Un recorrido para los sentidos por los puestos históricos de frutas tropicales, pescadería fresca y encurtidos del emblemático mercado. Pararemos a tomarnos un cartucho de pescaito frito en uno de los bares tradicionales del mercado y a charlar de lo que surja.",
    categoria: "Juegos",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Este Viernes a las 13:00",
    ubicacion: "Bajo la gran vidriera de colores del Mercado de Atarazanas",
    asistentesConfirmados: ["user-6", "user-1", "user-9"],
    maxAsistentes: 6,
    bannerUrl: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-24",
    creatorId: "user-8",
    title: "Senderismo y Atardecer en los Montes",
    description: "Una pequeña caminata de 4 km para subir a un mirador de los Montes de Málaga a ver el atardecer sobre toda la bahía de la ciudad. El cielo suele pintarse de tonos violetas y naranjas espectaculares. Una manera preciosa de acabar la jornada entre risas y silencio contemplativo.",
    categoria: "Bienestar",
    duracion: "3 horas",
    kronoValor: 30,
    fecha: "Próximo Sábado a las 19:30",
    ubicacion: "Mirador de Pocopan (Acceso Montes de Málaga)",
    asistentesConfirmados: ["user-8", "user-13", "user-10"],
    maxAsistentes: 12,
    bannerUrl: "https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  },
  {
    id: "plan-25",
    creatorId: "user-14",
    title: "Debate Amistoso de Cine Clásico",
    description: "Proponemos ver en casa previamente una obra maestra del suspense de Hitchcock y reunirnos en un café para debatir la trama, los planos y la música de forma amena, enriquecedora y divertida. ¡No necesitas ser ningún experto en cine para compartir tu punto de vista!",
    categoria: "Deportes",
    duracion: "2 horas",
    kronoValor: 20,
    fecha: "Próximo Martes a las 19:00",
    ubicacion: "Café de la Central en Calle Liborio García",
    asistentesConfirmados: ["user-14", "user-19", "user-4", "user-3"],
    maxAsistentes: 8,
    bannerUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800",
    chatHistory: []
  }
];

const rawMockSponsors: any[] = [
  {
    id: "spon-1",
    name: "Eva Málaga",
    offer: "Tarde Conceptual y 15% Descuento",
    description: "Espacio de moda, arte y eventos exclusivos en Málaga. Para planes creados con temática artística, visitas de diseño o mercadillos, venid a conocernos y os invitamos a un té matcha mientras disfrutáis de una guía de tendencias y un 15% de descuento grupal en prendas exclusivas de diseñadores locales.",
    logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUH8u16dwXY701-hVMDH9bZbPgcYpeyEsfJdbr6t2mEuDBwen_mM8PRHB1&s=10",
    bannerUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUH8u16dwXY701-hVMDH9bZbPgcYpeyEsfJdbr6t2mEuDBwen_mM8PRHB1&s=10",
    promoCode: "EVAGRUPO15",
    buttonText: "Obtener Código de Grupo",
    isReal: true,
    location: "Calle Carretería, 45, Málaga Centro"
  },
  {
    id: "spon-2",
    name: "Casa Kiki",
    offer: "Palmera de Chocolate Gigante Gratis",
    description: "Famosos en toda la provincia por nuestras icónicas Palmeras Gigantes de hojaldre artesanal. Si os apuntáis a un plan de merienda grupal a través de Gravita, os regalamos 1 Palmera Gigante de Chocolate o de Yema Tostada por cada compra de 4 cafés o batidos. ¡Perfecta para trocear y compartir entre amigos!",
    logoUrl: "https://casakiki.com/wp-content/uploads/2026/03/casa-kiki-palmeras-rellenas-gigantes.jpg",
    bannerUrl: "https://casakiki.com/wp-content/uploads/2026/03/casa-kiki-palmeras-rellenas-gigantes.jpg",
    promoCode: "KIKIPALMERA",
    buttonText: "Reservar Palmera de Grupo",
    isReal: true,
    location: "Calle Calderería, 9, Málaga Centro / Av. de la Estación, El Palo"
  },
  {
    id: "spon-3",
    name: "Waw Cafe",
    offer: "Promo Brunch 2x1 en Café de Especialidad",
    description: "Cafetería de especialidad con encanto, brunch delicioso y un espacio diseñado para el bienestar y la calma. Para vuestras quedadas matutinas o reuniones de lectura y charla en Gravita, os ofrecemos un 2x1 en cafés flat white, cold brew o infusiones al pedir tostadas de masa madre o bollería casera.",
    logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcDfU6p5d3TxPgaCDAnb3jpjBUXQWD6OsSdAR4gtR6gA&s=10",
    bannerUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcDfU6p5d3TxPgaCDAnb3jpjBUXQWD6OsSdAR4gtR6gA&s=10",
    promoCode: "WAWBRUNCH2X1",
    buttonText: "Obtener Código de Grupo",
    isReal: true,
    location: "Calle Tejón y Marín, 2, Málaga Centro"
  },
  {
    id: "spon-4",
    name: "Club Pádel El Candado",
    offer: "Pista y Palas Gratis por 2 Horas",
    description: "Club de tenis y pádel con espectaculares vistas al mar en Málaga Este. Reservad vuestro partidillo de iniciación en nuestra plataforma y os regalamos el alquiler de las palas y un bote de bolas para el grupo, además de un refresco de bienvenida en el bar del club.",
    logoUrl: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=150",
    bannerUrl: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&q=80&w=800",
    promoCode: "CANDADOPADEL",
    buttonText: "Reservar para el Plan",
    isReal: false,
    location: "Urbanización El Candado, Calle Golf, Málaga Este"
  },
  {
    id: "spon-5",
    name: "Librería Mapas y Compañía",
    offer: "Visita Privada y Obsequio de Guía Local",
    description: "Una de las librerías con más magia y encanto de Málaga, especializada en libros de viaje, globos terráqueos, juguetes antiguos y literatura de exploración. Para vuestros planes literarios, os ofrecemos una pequeña visita comentada de 10 minutos y un mapa ilustrado retro de Málaga de regalo.",
    logoUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=150",
    bannerUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=800",
    promoCode: "LIBRERIAMAPAS",
    buttonText: "Reservar Visita de Grupo",
    isReal: false,
    location: "Calle Compañía, 33, Málaga Centro"
  },
  {
    id: "spon-6",
    name: "Chiringuito El Tintero",
    offer: "Ración de Espetos Invitación de la Casa",
    description: "La joya de la gastronomía marinera en El Palo. Famosos por subastar los platos a viva voz. Venid con vuestro grupo de Gravita a almorzar, y el 'subastador' os obsequiará con una ración doble de espetos de sardinas malagueñas en vuestra mesa al cantar el código.",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/db/ElTintero-M%C3%A1laga.jpg",
    bannerUrl: "https://upload.wikimedia.org/wikipedia/commons/d/db/ElTintero-M%C3%A1laga.jpg",
    promoCode: "TINTEROESPETO",
    buttonText: "Obtener Código de Grupo",
    isReal: false,
    location: "Playa del Chanquete, El Palo, Málaga Este"
  },
  {
    id: "spon-7",
    name: "La Tapería del Soho",
    offer: "Tapa de Croquetas Caseras de Bienvenida",
    description: "Taberna con solera en pleno Soho que combina el encanto tradicional con toques modernos. Si creáis una quedada de amigos y cenáis con nosotros, os regalamos una bandeja de nuestras croquetas de jamón ibérico de bellota para compartir al centro.",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Croquetas-Jam%C3%B3n-Riofr%C3%ADo.jpg",
    bannerUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Croquetas-Jam%C3%B3n-Riofr%C3%ADo.jpg",
    promoCode: "CROQUETASOHO",
    buttonText: "Obtener Código de Grupo",
    isReal: false,
    location: "Calle Casas de Campos, 12, Soho Málaga"
  },
  {
    id: "spon-8",
    name: "Taller Al Andalus Cerámicas",
    offer: "Taller de Iniciación con 10% Descuento",
    description: "Aprende el arte mudéjar y la alfarería típica andaluza en un rincón con solera. Ofrecemos talleres de modelado y pintura de azulejos para grupos de amigos. Os ofrecemos un 10% de descuento y os podéis llevar vuestras piezas cocidas a casa de forma gratuita.",
    logoUrl: "https://images.unsplash.com/photo-1565192647048-f997ded87958?auto=format&fit=crop&q=80&w=150",
    bannerUrl: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&q=80&w=800",
    promoCode: "ALANDALUSART",
    buttonText: "Reservar para el Plan",
    isReal: false,
    location: "Calle San Juan, 18, Málaga Centro"
  }
];

export const mockSponsors: Sponsor[] = rawMockSponsors.map((spon, idx) => ({
  ...spon,
  kronoCost: [15, 25, 20, 15, 10, 20, 15, 10][idx % 8]
}));
