export interface User {
  id: string;
  name: string;
  age: number;
  profession: string;
  avatar: string;
  bio: string;
  interests: string[];
  kronos: number; // The user's Krono balance
}

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  senderId?: string;
  senderName: string;
  senderAvatar?: string;
  text: string;
  timestamp: string; // ISO string or short time like "14:32"
}

export interface Plan {
  id: string;
  creatorId: string; // ID of the User who created it
  title: string;
  description: string;
  categoria: string;
  fecha: string; // Date-time string (e.g., "Este Sábado a las 17:00")
  duracion: string; // Approximate duration (e.g. "2 horas")
  kronoValor: number; // Value in Kronos based on duration
  ubicacion: string;
  asistentesConfirmados: string[]; // array of User IDs
  maxAsistentes: number;
  bannerUrl?: string; // Optional custom banner URL (can be generated by Gemini!)
  chatHistory: Message[]; // Chat history for this plan's coordinator/group chat
  isPast?: boolean;
  attendanceVerified?: boolean;
  asistentesValidados?: string[];
}

export interface Sponsor {
  id: string;
  name: string;
  offer: string;
  description: string;
  logoUrl: string;
  bannerUrl: string;
  promoCode: string;
  buttonText: string;
  isReal: boolean;
  location: string;
  kronoCost: number; // Cost in Kronos to redeem this reward
}
